dist: trusty
sudo: required
language: java
jdk:
- openjdk8
addons:
  apt:
    packages:
    - rpm
    - expect
env:
  global:
  - LC_ALL=C
  - secure: "dXPIzaOC4+b5wkC1j3dBGo1AixUQlkulGq5KZiV3O8DIDZBUEu5Ok35bj4fT1gIJJ4o6ZywpFOFaz03J0LTj7Yjd4Y7x2sYxiV5L3NnmRdjR0RTtqDbxJ+QIOCRLFrjp6Pj9nYvjIBxQppzKMGKISXpJhU+VCIv3nQBCxF/C5qtUJqZ7DWM8AWi42sXA0+uDcT9D2HBD50f5AoppO72qrg/XoHA/NeHkwz8n1ibHNlRZpKIenV8HKY7d1t6L2MYlVTobwsEVBbgifyOYhZTVSDk3WSRRJCD8Z+gkcgMf9TS54ie4+TkL+r2g6VcIZFx/1k+FxjOxUG8iX4SbL9wbi9TQ3IvleDnTliSa08ixwVoWEl7DjINvYksH2F6lyE00/ZI42L/w3RJdblhQdDdctLvj6eE4UXxusjP1a4xAGjKb04isPkn7S4GPbcGb/4bhdHz4Hz+YAZu/IFK7D/ocibeJEJWNJRtb9Z/YEQnpYHxSC7/I8W3L+Prr8toAE7P+WIjBmDgJIae/BKk0dokNTT5gYLSMmRTbQQWqV1BsQRe1V/AikZf5c2j//x+qMN7CzJyROgHiWW4IkdqUaKCcCPXL2n8KvRjfzyhA7W4xpe1lO3w8cOzCAx6XHhcMdlW7mp++fPJR6Q5xBCa/HaPgSnqVsVWDJdEWIL5nxTj3y0E="
  - secure: "CEW201QsT8KhhhgGkx/kgV/y0ZoIfNXmFEGDCh0/bseTfqHS7Hxizfv9sWPA1bBvdVQ17V2mgFTAOpWqavLSggOuXQnCaPKeTYAFYwN2JUv7h/B+9556xrF2kVr3apM46zDCBuHq/AhjplhQXkgk+oaFriSb3rAMmX0j0vzw8/SwhG6VMfjfDa9pQyi/aWCx3GeUbrFHgcmIrAkVxZ+ImMt9t94YuTmguGOAiAxH2RWI22bLBuunc4zbbuXmmTf7lRq2EqWa+PKDCq/+XSLiYKzHBDenBdzWzx+QEZw3kRMqpIYtqvf8cMt/6lOktPGSvht70p7eNbETbzZpfWh6mylMtrc1cupUrdPAfDqPaxry9QaRJAcnatT4feTrBLNl8YQ4MnzlLznNzfruqnGnlq73IgYATHDBUA3HuJ33K8+hYmSe1lD4TdyG3ZhrvW3lXN00AzRU3+kLW7Q8y6Nu2pgGXd0MuWkMSBgY8OjZwysbntXTZwE2eczRjzS7RUWmRXVjjmcyRMhkXE7sjeFBmRvkqCoUKWFgVTYtP/e/LA2eWjylUi2WZtGbzs4X62mYbKcbSoy3Ir3SfK98byzC3WLLeJP1X9f5w6FvmTHZAw4WtimHXYu+bzCCbCoKsiA04KJsTVOZhOE9qUcPuFrAqWE8No+UQvhdqa9OH2+biww="
  - secure: "LQ370XZG//5b+OFWh+a0xBaltWf5MsVkxVoco8M/1z/Nwe9d5OBjF8w+9D4c+AiIUPKYuFWm6pvZkaRiQMQ3an6uClXnH8eApNDu3LjRnkwcpQy9XIDec4Yv2nJekMctnvUB4U7ByU1jvxkQhrJ0mtDRUgGAefGa5MNVroJ4Kz32L+YG1AtMRJjwrqAFyxTS5C3Y+4r7/vWpnJlFdhMHaGyHW8sml2Sym+V51F+2xQ6potExFabcc1jfz5sQu2tg2evLYpOlozDghwCK68EHlm3nQY6X9ZdiK/QE2wE9rf7UrOhYJMH3IXd3deaj4qfqh+FZraVGnXJjIu/BUITXwdsnrfNmfrwxha0pRSyDUqSqajHcp6YKCbvmHPV1F47KblHg78dgR+QkDyGeZrQqxjUR4JwN6A7B/+epYrRUo4yOU1K/AqSWktr1y1dZIvvRnVqM9PfdDwqCpmIpKNsjksmjdK0BIpb4KQq2aDjXGijyMtMBi5u11zB6YLX/tpzudREgEsCVoS+69/CUkAA6Py+fLcpHxJIpfD8nSP1WFPiK9Mw3eSn/Lx6IQCCmq2Fb0hymHRR7C48Oe7cQMm+QvL25dEjZ9vCejO02lnSyr8FSR9JL3CJUSkoOB7ZdQ9as23X8kxcj54yUITvDSTmTn7F1JaH/OfmA7vpJHxNBJRI="
install:
- git clone --branch 3.0 --depth=1 --no-single-branch https://github.com/Graylog2/graylog2-server
  ../graylog2-server
- "(cd ../graylog2-server && mvn -DskipTests=true compile -B -V)"
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -Dsource.skip=true
  -Dgpg.skip -B -V
script:
- mvn package -Dmaven.javadoc.skip=true -Dsource.skip=true -Dgpg.skip -B
after_success:
- openssl aes-256-cbc -K $encrypted_9cc1e0b2c494_key -iv $encrypted_9cc1e0b2c494_iv -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
- gpg2 --import deployment/signingkey.asc
- gpg2 --allow-secret-key-import --import deployment/signingkey.asc
before_deploy:
- mvn jdeb:jdeb --settings deployment/settings.xml && export RELEASE_DEB_FILE=$(ls
  target/*.deb)
- mvn rpm:rpm --settings deployment/settings.xml && export RELEASE_RPM_FILE=$(find
  target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: OriJjpQnuI5a2LqtfpaRLwfonNVRxDc+KgAnCT32x7FRsvmxu3d6Q0WQjgeAEeWQhcXlZJ/Bbylr4osQqirLmkVh98e3M2O3E4bGNuaCjbDecXrgPRAhMqnU1lzshhXwCM8jTcr1u7Vy/vVEenXYWHb3FUVatmoXYjj/t2JvkBKvmUC6F8zRZpaE7iqULYoF6J7WVh3BA7BkhG9vNPuQgzuRGIaUCex0YKhiIoZE/1G2dFWwHdpgpDDc6XNg8NADy+uxuU+n0MhNGb1OEMEouPZvEXyvkLS2PRp1WUZbTYJFBZWX/fNpoAnpjDPhSVUxFa/u6sDSBzNasQ34X9tPTzK83H5LwqA1HbmysvISD3Q2+q1liSO2UE+nVxaTsG6Whwe/9yWuBYewJpbdMeby8gRXWXTXy7aOWR3UDVq01tL5asl/jdBl92rOMRtzxp+IRxDfONtjGCMaNYCwen6pCxZoYyyHLajXMAtDOHHm4ciDi2mVzSd+nwrP3rI4WbuvdkVqAegoz7hz55UcRKaZ5X/OcNrXw46R5lQDSHOs6X2mT8B4Rv3JmT+tTg3Nj3ZtiDI/w4TnOdErgI9R9wyuVsUlcBBYyaQi4Jg9JjfrxZFEf0FeQDacUdapCy2VbmilAR6MACchUxydGDaTS8jF2LmC2GyMEH5cgQV7TfgPjSE=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_DEB_FILE}"
  - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    repo: airbus-cyber/graylog-plugin-ldap
    jdk: openjdk8
    tags: true
after_deploy:
- echo "Deploying release to Maven Central"
- mvn clean deploy -DskipTests=true --settings deployment/settings.xml
